#!/bin/sh

### BEGIN INIT INFO
# Provides:          batman
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Battery management
# Description:       Battery management program for Linux phones
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=batman
DAEMON=/usr/bin/$NAME
DESC="Battery management program for Linux phones"


[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions


case "$1" in
  start)
       start-stop-daemon --start --quiet --exec $DAEMON
    ;;
  stop)
      start-stop-daemon --stop --oknodo --exec $DAEMON --retry 30
    ;;
  force-reload|reload)
    exit 3
    ;;
  restart)
    $0 stop && $0 start
    ;;
  status)
    status_of_proc $DAEMON $NAME
    exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
