#!/bin/bash

CORE_FIRST=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | sed -n 1p)
CORE_LAST=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | tail -1)
UIDS=$(ls /run/user | head -1)

function governor() {
   for ((i=$CORE_FIRST;i<=$CORE_LAST; i++))
   do
       cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor /sys/devices/system/cpu/cpu$i/cpufreq/cpuinfo_cur_freq /sys/devices/system/cpu/cpu$i/online
   done
}

while [[ true ]];
do
    clear
    XDG_RUNTIME_DIR=/run/user/$UIDS/ wlr-randr | grep Enabled | cut -c 12-
    cat /sys/kernel/gpu/gpu_governor
    governor
    sleep 0.5
done
