#!/bin/bash

CORE_FIRST=$(awk '$1 == "processor" {print $3; exit}' /proc/cpuinfo)
CORE_LAST=$(awk '$1 == "processor" {print $3}' /proc/cpuinfo | tail -1)
UIDS=$(ls /run/user | head -1)

# x86 cpus have scaling_cur_freq instead of cpuinfo_cur_freq
if [ "$(uname -m)" = "x86_64" ] || [ "$(uname -m)" = "i686" ]; then
   CPUFREQ="scaling_cur_freq"
else
   CPUFREQ="cpuinfo_cur_freq"
fi

function governor() {
   for ((i=$CORE_FIRST;i<=$CORE_LAST; i++))
   do
       cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor /sys/devices/system/cpu/cpu$i/cpufreq/$CPUFREQ /sys/devices/system/cpu/cpu$i/online
   done
}

if [ -d /sys/class/devfreq/ ]; then
   DEVFREQ_GPU_PATH=$(find /sys/class/devfreq -name "*.gpu" -print -quit)
fi

gpu_governor_paths=(
  "/sys/class/kgsl/kgsl-3d0/devfreq/governor"
  "/sys/class/kgsl/kgsl-3d0/governor"
  "/sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor"
  "/sys/class/devfreq/5000000.qcom,kgsl-3d0/governor"
  "/sys/class/devfreq/ddr_devfreq/governor"
  "/sys/class/devfreq/graphics/governor"
  "/sys/kernel/gpu/gpu_governor"
  "$DEVFREQ_GPU_PATH/governor"
)

# Check each path for the GPU governor file
for path in "${gpu_governor_paths[@]}"; do
  if [ -f "$path" ]; then
    GPU_GOVERNOR_PATH="$path"
    break
  fi
done

# If no GPU governor file was found, unset the variable
if [ -z "$GPU_GOVERNOR_PATH" ]; then
  unset GPU_GOVERNOR_PATH
fi

if [ -d /sys/class/devfreq/soc:qcom,cci/ ]; then
   CCI=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpubw/ ]; then
   CPUBW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,gpubw/ ]; then
   GPUBW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,kgsl-busmon/ ]; then
   KGSL_BUSMON=true
fi

if [ -d /sys/class/devfreq/soc:qcom,mincpubw/ ]; then
   MINCPUBW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,l3-cpu0/ ]; then
   L3CPU0=true
fi

if [ -d /sys/class/devfreq/soc:qcom,l3-cpu6/ ]; then
   L3CPU6=true
fi

if [ -d /sys/class/devfreq/aa00000.qcom,vidc1:arm9_bus_ddr/ ]; then
   ARM9_BUS_DDR=true
fi

if [ -d /sys/class/devfreq/aa00000.qcom,vidc1:bus_cnoc/ ]; then
   BUS_CNOC=true
fi

if [ -d /sys/class/devfreq/aa00000.qcom,vidc1:venus_bus_ddr/ ]; then
   VENUS_BUS_DDR=true
fi

if [ -d /sys/class/devfreq/soc:qcom,l3-cdsp/ ]; then
   L3CDSP=true
fi

if [ -d /sys/class/devfreq/soc:qcom,memlat-cpu0/ ]; then
   MEMLAT_CPU0=true
fi

if [ -d /sys/class/devfreq/soc:qcom,memlat-cpu4/ ]; then
   MEMLAT_CPU4=true
fi

if [ -d /sys/class/devfreq/soc:qcom,memlat-cpu6/ ]; then
   MEMLAT_CPU6=true
fi

if [ -d /sys/class/devfreq/soc:qcom,mincpu0bw/ ]; then
   MINCPU0BW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,mincpu6bw/ ]; then
   MINCPU6BW=true
fi

if [ -d /sys/class/devfreq/soc:devfreq_spdm_cpu/ ]; then
   DEVFREQ_SPDM_CPU=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cdsp-cdsp-l3-lat/ ]; then
   CDSP_CDSP_L3_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-latfloor/ ]; then
   CPU0_CPU_DDR_LATFLOOR=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu0-cpu-l3-lat/ ]; then
   CPU0_CPU_L3_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu0-cpu-llcc-lat/ ]; then
   CPU0_CPU_LLCC_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/ ]; then
   CPU0_LLCC_DDR_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu6-cpu-ddr-latfloor/ ]; then
   CPU6_CPU_DDR_LATFLOOR=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu6-cpu-l3-lat/ ]; then
   CPU6_CPU_L3_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu6-cpu-llcc-lat/ ]; then
   CPU6_CPU_LLCC_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu6-llcc-ddr-lat/ ]; then
   CPU6_LLCC_DDR_LAT=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu-cpu-llcc-bw/ ]; then
   CPU_CPU_LLCC_BW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/ ]; then
   CPU_LLCC_DDR_BW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,npudsp-npu-ddr-bw/ ]; then
   NPUDSP_NPU_DDR_BW=true
fi

if [ -d /sys/class/devfreq/soc:qcom,npu-npu-ddr-bw/ ]; then
   NPU_NPU_DDR_BW=true
fi

if [ ! -z $GPU_GOVERNOR_PATH ]; then

   function gpugovernor() {
       echo "gpu governor"
       cat $GPU_GOVERNOR_PATH
   }

else

   function gpugovernor() {
       true
   }

fi

function busgovernor() {
    if [ "$CCI" == "true" ]; then
       echo "cci governor"
       cat /sys/class/devfreq/soc:qcom,cci/governor
    fi

    if [ "$CPUBW" == "true" ]; then
       echo "cpubw governor"
       cat /sys/class/devfreq/soc:qcom,cpubw/governor
    fi

    if [ "$GPUBW" == "true" ]; then
       echo "gpubw governor"
       cat /sys/class/devfreq/soc:qcom,gpubw/governor
    fi

    if [ "$KGSL_BUSMON" == "true" ]; then
       echo "kgsl-busmon governor"
       cat /sys/class/devfreq/soc:qcom,kgsl-busmon/governor
    fi

    if [ "$MINCPUBW" == "true" ]; then
       echo "mincpubw governor"
       cat /sys/class/devfreq/soc:qcom,mincpubw/governor
    fi

    if [ "$L3CPU0" == "true" ]; then
       echo "l3cpu0 governor"
       cat /sys/class/devfreq/soc:qcom,l3-cpu0/governor
    fi

    if [ "$L3CPU6" == "true" ]; then
       echo "l3cpu6 governor"
       cat /sys/class/devfreq/soc:qcom,l3-cpu6/governor
    fi

    if [ "$ARM9_BUS_DDR" == "true" ]; then
       echo "arm9_bus_ddr governor"
       cat /sys/class/devfreq/aa00000.qcom,vidc1:arm9_bus_ddr/governor
    fi

    if [ "$BUS_CNOC" == "true" ]; then
       echo "bus_cnoc governor"
       cat /sys/class/devfreq/aa00000.qcom,vidc1:bus_cnoc/governor
    fi

    if [ "$VENUS_BUS_DDR" == "true" ]; then
       echo "venus_bus_ddr governor"
       cat /sys/class/devfreq/aa00000.qcom,vidc1:venus_bus_ddr/governor
    fi

    if [ "$L3CDSP" == "true" ]; then
       echo "l3cdsp governor"
       cat /sys/class/devfreq/soc:qcom,l3-cdsp/governor
    fi

    if [ "$MEMLAT_CPU0" == "true" ]; then
       echo "memlat_cpu0 governor"
       cat /sys/class/devfreq/soc:qcom,memlat-cpu0/governor
    fi

    if [ "$MEMLAT_CPU4" == "true" ]; then
       echo "memlat_cpu4 governor"
       cat /sys/class/devfreq/soc:qcom,memlat-cpu4/governor
    fi

    if [ "$MEMLAT_CPU6" == "true" ]; then
       echo "memlat_cpu6 governor"
       cat /sys/class/devfreq/soc:qcom,memlat-cpu6/governor
    fi

    if [ "$MINCPU0BW" == "true" ]; then
       echo "mincpu0bw governor"
       cat /sys/class/devfreq/soc:qcom,mincpu0bw/governor
    fi

    if [ "$MINCPU6BW" == "true" ]; then
       echo "mincpu6bw governor"
       cat /sys/class/devfreq/soc:qcom,mincpu6bw/governor
    fi

    if [ "$DEVFREQ_SQPM_CPU" == "true" ]; then
       echo "devfreq_spdm_cpu governor"
       cat /sys/class/devfreq/soc:devfreq_spdm_cpu/governor
    fi

    if [ "CDSP_CDSP_L3_LAT" == "true" ]; then
       echo "cdsp-cdsp-l3-lat governor"
       cat /sys/class/devfreq/soc:qcom,cdsp-cdsp-l3-lat/governor
    fi

    if [ "CPU0_CPU_DDR_LATFLOOR" == "true" ]; then
       echo "cpu0-cpu-ddr-latfloor governor"
       cat /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-latfloor/governor
    fi

    if [ "CPU0_CPU_L3_LAT" == "true" ]; then
       echo "cpu0-cpu-l3-lat governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu0-cpu-l3-lat/governor
    fi

    if [ "CPU0_CPU_LLCC_LAT" == "true" ]; then
       echo "cpu0-cpu-llcc-lat governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu0-cpu-llcc-lat/governor
    fi

    if [ "CPU0_LLCC_DDR_LAT" == "true" ]; then
       echo "cpu0-llcc-ddr-lat governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/governor
    fi

    if [ "CPU6_CPU_DDR_LATFLOOR" == "true" ]; then
       echo "cpu6-cpu-ddr-latfloor governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu6-cpu-ddr-latfloor/governor
    fi

    if [ "CPU6_CPU_L3_LAT" == "true" ]; then
       echo "cpu6-cpu-l3-lat governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu6-cpu-l3-lat/governor
    fi

    if [ "CPU6_CPU_LLCC_LAT" == "true" ]; then
       echo "cpu6-cpu-llcc-lat governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu6-cpu-llcc-lat/governor
    fi

    if [ "CPU6_LLCC_DDR_LAT" == "true" ]; then
       echo "cpu6-llcc-ddr-lat governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu6-llcc-ddr-lat/governor
    fi

    if [ "CPU_CPU_LLCC_BW" == "true" ]; then
       echo "cpu-llcc-ddr-bw governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu-cpu-llcc-bw/governor
    fi

    if [ "CPU_LLCC_DDR_BW" == "true" ]; then
       echo "cpu-llcc-ddr-bw governor"
       echo powersave > /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/governor
    fi

    if [ "NPUDSP_NPU_DDR_BW" == "true" ]; then
       echo "npudsp-npu-ddr-bw governor"
       echo powersave > /sys/class/devfreq/soc:qcom,npudsp-npu-ddr-bw/governor
    fi

    if [ "NPU_NPU_DDR_BW" == "npudsp-npu-ddr-bwtrue" ]; then
       echo "npu-npu-ddr-bw governor"
       echo powersave > /sys/class/devfreq/soc:qcom,npu-npu-ddr-bw/governor
    fi
}


while [[ true ]];
do
    clear
    clear
    echo -n "screen status [enabled]: "
    XDG_RUNTIME_DIR=/run/user/$UIDS/ wlr-randr | sed -n '/Enabled/s/^.\{11\}//p'
    governor
    gpugovernor
    busgovernor
    sleep 0.5
done
