#!/bin/bash

CORE_FIRST=$(awk '$1 == "processor" {print $3; exit}' /proc/cpuinfo)
CORE_LAST=$(awk '$1 == "processor" {print $3}' /proc/cpuinfo | tail -1)
UIDS=$(ls /run/user | head -1)

function governor() {
   for ((i=$CORE_FIRST;i<=$CORE_LAST; i++))
   do
       cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor /sys/devices/system/cpu/cpu$i/cpufreq/cpuinfo_cur_freq /sys/devices/system/cpu/cpu$i/online
   done
}

while [[ true ]];
do
    clear
    XDG_RUNTIME_DIR=/run/user/$UIDS/ wlr-randr | sed -n '/Enabled/s/^.\{11\}//p'
    if [ -f /sys/kernel/gpu/gpu_governor ]; then
       cat /sys/kernel/gpu/gpu_governor
    fi
    governor
    sleep 0.5
done
