#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2023 Bardia Moshiri <fakeshell@bardia.tech>

# Basic help function
help() {
  cat <<EOF
batman, a battery management program originally intended for Droidian

Usage: batman
EOF
  exit 0
}

# Bumped at every commit
version() {
   echo "1.42"
   exit 0
}

if [ -r "/dev/tty0" ]; then
    delay() {
        read -t "$1" < /dev/tty0
    }
else
    delay() {
        sleep "$1"
    }
fi

# First check if user is asking for help or version if not move on.
case "$1" in
  -h|-\?|--help)
    help
    ;;
  -v|--version)
    version
    ;;
esac

# CORE_FIRST will read cpuinfo and get the first cpu core number at boot. (we know its 0 but just in case to be 100% safe)
# CORE_LAST will read cpuinfo and get the last cpu core number at boot.
# UIDS will list users from /run/user to later use with wlrdisplay or wlr-randr
# DEFAULT_GOVERNOR stores the default cpu governor used by the device.
# AVUSER will get the number of active user sessions. It's used later on to make sure there is only one active user with a session.
# AVPOL will check for the amount of cpu policy groups. It's used later on to disable offlining on devices with a single group.
# FIRSTPOL will get the first policy group. (this group stores LITTLE cores)
# FIRSTPOLCORE will get the first cpu core of policy group one.
# LASTPOLCORE will get the last cpu core of policy group one.
# UPTIME is just uptime of the system in minutes.
CORE_FIRST=$(awk '$1 == "processor" {print $3; exit}' /proc/cpuinfo)
CORE_LAST=$(awk '$1 == "processor" {print $3}' /proc/cpuinfo | tail -1)
UIDS=$(ls /run/user | head -1)
ARCH=$(uname -m)

# x86 cpus have powersave and performance governors, check architecture and set the governor accordingly.
if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
   if grep -q "performance" /sys/devices/system/cpu/cpu$CORE_FIRST/cpufreq/scaling_available_governors; then
      if grep -q "powersave" /sys/devices/system/cpu/cpu$CORE_FIRST/cpufreq/scaling_governor; then
         DEFAULT_GOVERNOR="powersave"
      else
         DEFAULT_GOVERNOR="performance"
      fi
   else
      echo "can't find the right governor. exiting"
      exit 0
   fi
else
   DEFAULT_GOVERNOR=$(</sys/devices/system/cpu/cpu$CORE_FIRST/cpufreq/scaling_governor)
fi

AVUSER=$(ls /run/user | wc -l)
AVPOL=$(ls /sys/devices/system/cpu/cpufreq | grep -c policy)
UPTIME=$(awk '{print int($1)/60}' /proc/uptime | cut -f 1 -d .)

# Exynos chips require special configuration and governors, usually device tree has the chipset name in the model section.
if [ -f /proc/device-tree/model ]; then
    if grep -q -i "EXYNOS" /proc/device-tree/model; then
       IS_EXYNOS=true
    else
       IS_EXYNOS=false
    fi
fi

# Make sure the required directory exists.
if [ ! -d /var/lib/batman/ ]; then
   mkdir -p /var/lib/batman/
fi

# Parse our config file.
if [ -f /var/lib/batman/config ]; then
   source <(tail -n +2 /var/lib/batman/config)
else
   echo "config file does not exist. using default values"
fi

# Check if there are any policies available.
if [[ "$AVPOL" != "0" ]]; then
   if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
      FIRSTPOL=$(ls /sys/devices/system/cpu/cpufreq | grep policy | head -1)
      FIRSTPOLCORE=1
      LASTPOLCORE="$CORE_LAST"
   else
      FIRSTPOL=$(ls /sys/devices/system/cpu/cpufreq | grep policy | head -1)
      FIRSTPOLCORE=$(cut -c1 - < /sys/devices/system/cpu/cpufreq/$FIRSTPOL/related_cpus)
      LASTPOLCORE=$(awk '{for(i=NF;i>=1;i--) printf("%s ", $i)}' /sys/devices/system/cpu/cpufreq/$FIRSTPOL/related_cpus | cut -c1 -)
   fi
# Support for older arm devices such as MSM8996.
elif [[ "$AVPOL" == "0" ]] && [ -f "/sys/devices/system/cpu/cpufreq/all_time_in_state" ]; then
   LEGACY=true
   STATE=$(grep "cpu" /sys/devices/system/cpu/cpufreq/all_time_in_state | wc -w)

   # Just a bit of info for debugging. can be used later on.
   for ((i=2; i<=$STATE; i++))
   do
      awk -v col_num="$i" 'NR>1 {print $col_num}' /sys/devices/system/cpu/cpufreq/all_time_in_state &> /var/lib/batman/LEGACY-CPU-$(($i - 2))
   done

   FIRSTPOLCORE="$CORE_FIRST"
   LASTPOLCORE=$(($CORE_LAST/2))
else
   echo "no cpu policies available. exiting"
   exit 0
fi

if [ -f /var/lib/batman/exynos_cpu_limit ]; then
   if [ -f /sys/power/cpufreq_min_limit ]; then
      CPUSAVEGOVERNOR="exynos_cpu_limit"
      CPUFREQ_MIN_LIMIT=$(</sys/power/cpufreq_min_limit)
      CPUFREQ_MAX_LIMIT=$(</sys/power/cpufreq_max_limit)
   fi
fi

# Check if powersave governor is available.
if [ "$LEGACY" == "true" ] && [ -z "$CPUSAVEGOVERNOR" ]; then
   if grep -q powersave /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors; then
      CPUSAVEGOVERNOR="powersave"
   elif grep -q userspace /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors; then
      CPUSAVEGOVERNOR="userspace"
   else
      echo "powersave or userspace are not available governors on this system. exiting"
      exit 0
   fi
elif [ -z "$CPUSAVEGOVERNOR" ]; then
   if grep -q powersave /sys/devices/system/cpu/cpufreq/$FIRSTPOL/scaling_available_governors; then
      CPUSAVEGOVERNOR="powersave"
   elif grep -q userspace /sys/devices/system/cpu/cpufreq/$FIRSTPOL/scaling_available_governors; then
      CPUSAVEGOVERNOR="userspace"
   else
      echo "powersave or userspace are not available governors on this system. exiting"
      exit 0
   fi
fi

# Use either upower client or our own upower wrapper
if [[ $(which batman-helper) ]]; then
   BATMAN_OUTPUT=$(batman-helper battery)
   if [[ $? -eq 0 ]] && [ ! -z "$BATMAN_OUTPUT" ]; then
      echo "using batman-helper for charging status"
      GET_CHARGE="batman-helper battery"
      touch /var/lib/batman/using-batman-helper-for-charge
   fi
fi

if [ -z "$GET_CHARGE" ] && [[ $(which upower) ]]; then
   GET_CHARGE='upower -d | awk '\''{if(/state/){if(!seen[$0]){seen[$0]=1;print substr($0,26);exit}}}'\'
   GET_CHARGE_FALLBACK='upower -i /org/freedesktop/UPower/devices/battery_battery | awk '\''{if(/state/){if(!seen[$0]){seen[$0]=1;print substr($0,26);exit}}}'\'

   CHARGE_STATUS=$(eval $GET_CHARGE)
   CHARGE_STATUS_FALLBACK=$(eval $GET_CHARGE_FALLBACK)
   if [ "$CHARGE_STATUS" == "discharging" ] || [ "$CHARGE_STATUS" == "fully-charged" ] || [ "$CHARGE_STATUS" == "charging" ]; then
      rm /var/lib/batman/using-batman-helper-for-charge -f
   elif [ "$CHARGE_STATUS_FALLBACK" == "discharging" ] || [ "$CHARGE_STATUS_FALLBACK" == "fully-charged" ] || [ "$CHARGE_STATUS_FALLBACK" == "charging" ]; then
      rm /var/lib/batman/using-batman-helper-for-charge -f
      echo "Falling back to /org/freedesktop/UPower/devices/battery_battery"
      GET_CHARGE='upower -i /org/freedesktop/UPower/devices/battery_battery | awk '\''{if(/state/){if(!seen[$0]){seen[$0]=1;print substr($0,26);exit}}}'\'
   fi
elif [ -z "$GET_CHARGE" ]; then
   echo "neither batman-helper nor upower is available. exiting"
   exit 0
fi

# Use either wlrdisplay or wlr-randr
if [[ $(which batman-helper) ]]; then
   eval "XDG_RUNTIME_DIR=/run/user/\$UIDS/ $(which batman-helper) wlrdisplay" &> /var/lib/batman/wlrfirstcheck
   if [[ $? -eq 0 ]]; then
      echo "using batman-helper for screen status"
      GET_SCREEN="XDG_RUNTIME_DIR=/run/user/\$UIDS/ batman-helper wlrdisplay"
      touch /var/lib/batman/using-batman-helper-for-screen
      WLRTOOL=true
   elif [[ $? -eq 1 ]]; then
      if grep -q "wlrdisplay support is not enabled." /var/lib/batman/wlrfirstcheck; then
         if [[ $(which wlr-randr) ]]; then
            GET_SCREEN="XDG_RUNTIME_DIR=/run/user/\$UIDS/ wlr-randr | sed -n '/Enabled/s/^.\{11\}//p'"
            rm /var/lib/batman/using-batman-helper-for-screen -f
            WLRTOOL=true
         fi
      else
         WLRTOOL=false
      fi
   fi
elif [[ $(which wlr-randr) ]]; then
   GET_SCREEN="XDG_RUNTIME_DIR=/run/user/\$UIDS/ wlr-randr | sed -n '/Enabled/s/^.\{11\}//p'"
   rm /var/lib/batman/using-batman-helper-for-screen -f
   WLRTOOL=true
else
   WLRTOOL=false
fi

# Check if system is using a wlroots based desktop environment.
if [ "$WLRTOOL" == "true" ]; then
   eval "$GET_SCREEN" &> /var/lib/batman/wlrcheck

   if grep -q "compositor doesn't support" /var/lib/batman/wlrcheck; then
      WLROOTS=false
   elif grep -q "wl_display_dispatch failed" /var/lib/batman/wlrcheck; then
      WLROOTS=false
   else
      WLROOTS=true
   fi
else
   WLROOTS=false
fi

# Check if wlroots based environment has started. if not wait a bit and retry.
if [ "$WLROOTS" == "true" ]; then
   while [[ true ]]
   do
      eval "$GET_SCREEN" &> /dev/null

      if [ $? -eq 0 ]; then
         # If the exit status is 0, break out of the loop
         break
      else
         # If the exit status is not 0, wait for some time and try again
         delay 10
      fi
   done
# Check if system is using KDE Plasma.
elif [ "$WLROOTS" == "false" ] && [[ $(which kscreen-doctor) ]]; then
   if XDG_SESSION_TYPE=wayland XDG_RUNTIME_DIR=/run/user/$UIDS/ kscreen-doctor -o 2>/dev/null | grep Output >/dev/null 2>&1; then
      USERNAME=$(id -un $UIDS)
      GET_SCREEN="sudo -u $USERNAME DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/$UIDS/bus' qdbus org.kde.screensaver /ScreenSaver org.freedesktop.ScreenSaver.GetActive"
      KDE=true
   else
      KDE=false
   fi
fi

if [[ $(which batman-helper) ]]; then
   echo "using batman-helper for CPU usage"
   GET_CPU_USAGE="batman-helper cpu"
   touch /var/lib/batman/using-batman-helper-for-cpu
else
   GET_CPU_USAGE="awk '{u=\$2+\$4; t=\$2+\$4+\$5; if (NR==1){u1=u; t1=t;} else print (\$2+\$4-u1) * 100 / (t-t1) ; }' <(grep 'cpu ' /proc/stat) <(sleep 0.2; grep 'cpu ' /proc/stat) | cut -d '.' -f1"
   rm /var/lib/batman/using-batman-helper-for-cpu -f
fi

# If none of the supported compositors are used then exit.
if [ "$KDE" == "false" ] && [ "$WLROOTS" == "false" ]; then
   echo "Display server not supported. exiting"
   exit 0
fi

# Use our AVUSER variable to make sure only one active user session exists.
if [[ "$AVUSER" -gt "1" ]]; then
   echo "more than one user active. waiting for the other user profile to disappear"
   while true
   do
      AVUSER=$(ls /run/user | wc -l)
      if [[ "$AVUSER" -gt "1" ]]; then
         delay 10
      else
         echo "other user disappeared. starting"
         break
      fi
   done
fi

if [ -z "$(eval $GET_CHARGE)" ]; then
   echo "No battery found in this device. exiting"
   exit 0
fi

# Make sure that our OFFLINE variable is set from the config file if not use default value.
if [ -z "$OFFLINE" ]; then
   echo "Setting the default value of OFFLINE as true"
   OFFLINE=true
fi

# Use our AVPOL variable to make sure our device has more than one policy groups.
# If there was only one set the variable to not offline any cpu cores.
if [[ "$AVPOL" -eq "1" ]]; then
   echo "Only one cpu policy group detected, disabling cpu offlining"
   OFFLINE=false
fi

# Make sure that our POWERSAVE variable is set from the config file if not use default value.
if [ -z "$POWERSAVE" ]; then
   echo "Setting the default value of POWERSAVE as true"
   POWERSAVE=true
fi

# Make sure that our MAX_CPU_USAGE variable is set from the config file if not use default value.
if [ -z "$MAX_CPU_USAGE" ]; then
   echo "Setting the default value of MAX_CPU_USAGE as 60"
   MAX_CPU_USAGE=60
fi

# Make sure that our CHARGESAVE variable is set from the config file if not use default value.
if [ -z "$CHARGESAVE" ]; then
   echo "Setting the default value of CHARGESAVE as true"
   CHARGESAVE=true
fi

# Make sure that our GPUSAVE variable is set from the config file if not use default value.
if [ -z "$GPUSAVE" ]; then
   echo "Setting the default value of GPUSAVE as true"
   GPUSAVE=true
fi

# Make sure that our BUSSAVE variable is set from the config file if not use default value.
if [ -z "$BUSSAVE" ]; then
   echo "Setting the default value of BUSSAVE as true"
   BUSSAVE=true
fi

# Make sure MAX_CPU_USAGE is a number betweem 0 and 100
if ! [[ "$MAX_CPU_USAGE" =~ ^[0-9]+$ ]] || [[ "$MAX_CPU_USAGE" -lt 0 ]] || [[ "$MAX_CPU_USAGE" -gt 100 ]]; then
    echo "bad MAX_CPU_USAGE value. defaulting to 60"
    MAX_CPU_USAGE=60
fi

# Make sure that our BUSSAVE variable is set from the config file if not use default value.
if [ -z "$BTSAVE" ]; then
   echo "Setting the default value of BTSAVE as true"
   BTSAVE=true
fi

# Set up an array with the GPU governor file paths to check
gpu_governor_paths=(
  "/sys/class/kgsl/kgsl-3d0/devfreq/governor"
  "/sys/class/kgsl/kgsl-3d0/governor"
  "/sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor"
  "/sys/class/devfreq/5000000.qcom,kgsl-3d0/governor"
  "/sys/class/devfreq/ddr_devfreq/governor"
  "/sys/class/devfreq/graphics/governor"
  "/sys/kernel/gpu/gpu_governor"
  "$DEVFREQ_GPU_PATH/governor"
)

# Loop through the GPU governor file paths and check if each file exists
for gpu_governor_path in "${gpu_governor_paths[@]}"; do
    if [ -f "$gpu_governor_path" ]; then
       CAN_GPUSAVE=true
       DEFAULT_GPU_GOVERNOR=$(<"$gpu_governor_path")
       GPU_GOVERNOR_PATH="$gpu_governor_path"
       break
    fi
done

# If none of the GPU governor files were found, set CAN_GPUSAVE to false
if [ -z "$DEFAULT_GPU_GOVERNOR" ]; then
  CAN_GPUSAVE=false
fi

# If powersave is not a governor in the GPU profile then disable this feature.
if [ $CAN_GPUSAVE == "true" ]; then
   if ! grep -q "powersave" $GPU_GOVERNOR_PATH; then
      CAN_GPUSAVE=false
   fi
fi

if ! which bluetoothctl &> /dev/null; then
    echo "bluetoothctl does not exist, setting BTSAVE to false"
    BTSAVE=false
else
    if ! bluetoothctl info | grep -q 'Connected:'; then
        BTSTAT="off"
    else
        BTSTAT="on"
    fi
fi

# Check for bus governor nodes, if available then we'll powersave them too!
if [ -d /sys/class/devfreq/ ]; then
   if [ -d /sys/class/devfreq/soc:qcom,cci/ ]; then
      CCI=true
      DEFAULT_CCI_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cci/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpubw/ ]; then
      CPUBW=true
      DEFAULT_CPUBW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpubw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,gpubw/ ]; then
      GPUBW=true
      DEFAULT_GPUBW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,gpubw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,kgsl-busmon/ ]; then
      KGSL_BUSMON=true
      DEFAULT_KGSL_BUSMON_GOVERNOR=$(</sys/class/devfreq/soc:qcom,kgsl-busmon/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,mincpubw/ ]; then
      MINCPUBW=true
      DEFAULT_MINCPUBW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,mincpubw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,l3-cpu0/ ]; then
      L3CPU0=true
      DEFAULT_L3CPU0_GOVERNOR=$(</sys/class/devfreq/soc:qcom,l3-cpu0/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,l3-cpu6/ ]; then
      L3CPU6=true
      DEFAULT_L3CPU6_GOVERNOR=$(</sys/class/devfreq/soc:qcom,l3-cpu6/governor)
   fi

   if [ -d /sys/class/devfreq/aa00000.qcom,vidc1:arm9_bus_ddr/ ]; then
      ARM9_BUS_DDR=true
      DEFAULT_ARM9_BUS_DDR_GOVERNOR=$(</sys/class/devfreq/aa00000.qcom,vidc1:arm9_bus_ddr/governor)
   fi

   if [ -d /sys/class/devfreq/aa00000.qcom,vidc1:bus_cnoc/ ]; then
      BUS_CNOC=true
      DEFAULT_BUS_CNOC_GOVERNOR=$(</sys/class/devfreq/aa00000.qcom,vidc1:bus_cnoc/governor)
   fi

   if [ -d /sys/class/devfreq/aa00000.qcom,vidc1:venus_bus_ddr/ ]; then
      VENUS_BUS_DDR=true
      DEFAULT_VENUSBUSDDR_GOVERNOR=$(</sys/class/devfreq/aa00000.qcom,vidc1:venus_bus_ddr/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,l3-cdsp/ ]; then
      L3CDSP=true
      DEFAULT_L3CDSP_GOVERNOR=$(</sys/class/devfreq/soc:qcom,l3-cdsp/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,memlat-cpu0/ ]; then
      MEMLAT_CPU0=true
      DEFAULT_MEMLAT_CPU0_GOVERNOR=$(</sys/class/devfreq/soc:qcom,memlat-cpu0/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,memlat-cpu4/ ]; then
      MEMLAT_CPU4=true
      DEFAULT_MEMLAT_CPU4_GOVERNOR=$(</sys/class/devfreq/soc:qcom,memlat-cpu4/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,memlat-cpu6/ ]; then
      MEMLAT_CPU6=true
      DEFAULT_MEMLAT_CPU6_GOVERNOR=$(</sys/class/devfreq/soc:qcom,memlat-cpu6/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,mincpu0bw/ ]; then
      MINCPU0BW=true
      DEFAULT_MINCPU0BW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,mincpu0bw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,mincpu6bw/ ]; then
      MINCPU6BW=true
      DEFAULT_MINCPU6BW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,mincpu6bw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:devfreq_spdm_cpu/ ]; then
      DEVFREQ_SPDM_CPU=true
      DEFAULT_DEVFREQ_SPDM_CPU_GOVERNOR=$(</sys/class/devfreq/soc:devfreq_spdm_cpu/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cdsp-cdsp-l3-lat/ ]; then
      CDSP_CDSP_L3_LAT=true
      DEFAULT_CDSP_CDSP_L3_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cdsp-cdsp-l3-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-latfloor/ ]; then
      CPU0_CPU_DDR_LATFLOOR=true
      DEFAULT_CPU0_CPU_DDR_LATFLOOR_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-latfloor/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu0-cpu-l3-lat/ ]; then
      CPU0_CPU_L3_LAT=true
      DEFAULT_CPU0_CPU_L3_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu0-cpu-l3-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu0-cpu-llcc-lat/ ]; then
      CPU0_CPU_LLCC_LAT=true
      DEFAULT_CPU0_CPU_LLCC_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu0-cpu-llcc-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/ ]; then
      CPU0_LLCC_DDR_LAT=true
      DEFAULT_CPU0_LLCC_DDR_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu6-cpu-ddr-latfloor/ ]; then
      CPU6_CPU_DDR_LATFLOOR=true
      DEFAULT_CPU6_CPU_DDR_LATFLOOR_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu6-cpu-ddr-latfloor/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu6-cpu-l3-lat/ ]; then
      CPU6_CPU_L3_LAT=true
      DEFAULT_CPU6_CPU_L3_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu6-cpu-l3-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu6-cpu-llcc-lat/ ]; then
      CPU6_CPU_LLCC_LAT=true
      DEFAULT_CPU6_CPU_LLCC_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu6-cpu-llcc-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu6-llcc-ddr-lat/ ]; then
      CPU6_LLCC_DDR_LAT=true
      DEFAULT_CPU6_LLCC_DDR_LAT_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu6-llcc-ddr-lat/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu-cpu-llcc-bw/ ]; then
      CPU_CPU_LLCC_BW=true
      DEFAULT_CPU_CPU_LLCC_BW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu-cpu-llcc-bw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/ ]; then
      CPU_LLCC_DDR_BW=true
      DEFAULT_CPU_LLCC_DDR_BW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,npudsp-npu-ddr-bw/ ]; then
      NPUDSP_NPU_DDR_BW=true
      DEFAULT_NPUDSP_NPU_DDR_BW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,npudsp-npu-ddr-bw/governor)
   fi

   if [ -d /sys/class/devfreq/soc:qcom,npu-npu-ddr-bw/ ]; then
      NPU_NPU_DDR_BW=true
      DEFAULT_NPU_NPU_DDR_BW_GOVERNOR=$(</sys/class/devfreq/soc:qcom,npu-npu-ddr-bw/governor)
   fi
fi

# Declare an array with the configuration values
declare -A governors=(
  ["GPUSAVE"]=$DEFAULT_GPU_GOVERNOR
  ["CCI"]=$DEFAULT_CCI_GOVERNOR
  ["CPUBW"]=$DEFAULT_CPUBW_GOVERNOR
  ["GPUBW"]=$DEFAULT_GPUBW_GOVERNOR
  ["KGSL_BUSMON"]=$DEFAULT_KGSL_BUSMON_GOVERNOR
  ["MINCPUBW"]=$DEFAULT_MINCPUBW_GOVERNOR
  ["L3CPU0"]=$DEFAULT_L3CPU0_GOVERNOR
  ["L3CPU6"]=$DEFAULT_L3CPU6_GOVERNOR
  ["ARM9_BUS_DDR"]=$DEFAULT_ARM9_BUS_DDR_GOVERNOR
  ["BUS_CNOC"]=$DEFAULT_BUS_CNOC_GOVERNOR
  ["VENUS_BUS_DDR"]=$DEFAULT_VENUS_BUS_DDR_GOVERNOR
  ["L3CDSP"]=$DEFAULT_L3CDSP_GOVERNOR
  ["MEMLAT_CPU0"]=$DEFAULT_MEMLAT_CPU0_GOVERNOR
  ["MEMLAT_CPU4"]=$DEFAULT_MEMLAT_CPU4_GOVERNOR
  ["MEMLAT_CPU6"]=$DEFAULT_MEMLAT_CPU6_GOVERNOR
  ["MINCPU0BW"]=$DEFAULT_MINCPU0BW_GOVERNOR
  ["MINCPU6BW"]=$DEFAULT_MINCPU6BW_GOVERNOR
  ["DEVFREQ_SQPM_CPU"]=$DEFAULT_DEVFREQ_SQPM_CPU_GOVERNOR
  ["CDSP_CDSP_L3_LAT"]=$DEFAULT_CDSP_CDSP_L3_LAT_GOVERNOR
  ["CPU0_CPU_DDR_LATFLOOR"]=$DEFAULT_CPU0_CPU_DDR_LATFLOOR_GOVERNOR
  ["CPU0_CPU_L3_LAT"]=$DEFAULT_CPU0_CPU_L3_LAT_GOVERNOR
  ["CPU0_CPU_LLCC_LAT"]=$DEFAULT_CPU0_CPU_LLCC_LAT_GOVERNOR
  ["CPU0_LLCC_DDR_LAT"]=$DEFAULT_CPU0_LLCC_DDR_LAT_GOVERNOR
  ["CPU6_CPU_DDR_LATFLOOR"]=$DEFAULT_CPU6_CPU_DDR_LATFLOOR_GOVERNOR
  ["CPU6_CPU_L3_LAT"]=$DEFAULT_CPU6_CPU_L3_LAT_GOVERNOR
  ["CPU6_CPU_LLCC_LAT"]=$DEFAULT_CPU6_CPU_LLCC_LAT_GOVERNOR
  ["CPU6_LLCC_DDR_LAT"]=$DEFAULT_CPU6_LLCC_DDR_LAT_GOVERNOR
  ["CPU_CPU_LLCC_BW"]=$DEFAULT_CPU_CPU_LLCC_BW_GOVERNOR
  ["CPU_LLCC_DDR_BW"]=$DEFAULT_CPU_LLCC_DDR_BW_GOVERNOR
  ["NPUDSP_NPU_DDR_BW"]=$DEFAULT_NPUDSP_NPU_DDR_BW_GOVERNOR
  ["NPU_NPU_DDR_BW"]=$DEFAULT_NPU_NPU_DDR_BW_GOVERNOR
)

# Copy default governor to a file to use it later on if the service gets restarted unexpectedly.
if [ ! -f /var/lib/batman/saved ]; then
   if [ "$DEFAULT_GOVERNOR" == "powersave" ]; then
      if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
         echo "$DEFAULT_GOVERNOR" > /var/lib/batman/default_cpu_governor
      else
         echo "bad starting governor. exiting"
         exit 0
      fi
   else
      echo "$DEFAULT_GOVERNOR" > /var/lib/batman/default_cpu_governor
   fi

   for gov in "${!governors[@]}"; do
      if [ "${!gov}" == "true" ]; then
        lowercase=$(echo "${gov,,}") # convert to lowercase
        echo "${governors[$gov]}" > "/var/lib/batman/default_${lowercase}_governor"
      fi
   done

   touch /var/lib/batman/saved
# In case of bad governor values choose the right value or exit if it fails to do so.
elif [[ "$DEFAULT_GOVERNOR" == "powersave" ]]; then
   if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
      true
   elif [[ $(</var/lib/batman/default_cpu_governor)  == "powersave" ]]; then
      echo "bad starting governor. exiting"
      exit 0
   else
      DEFAULT_GOVERNOR=$(</var/lib/batman/default_cpu_governor)
   fi
fi

# Loop over the array and check each variable
for var in "${!governors[@]}"; do
    if [ "${!var}" == "true" ] && [ "${governors[$var]}" == "powersave" ]; then
        if [[ $(<"/var/lib/batman/default_${var,,}_governor") == "powersave" ]]; then
            echo "bad ${var,,} governor. disabling ${var,,} powersave"
            eval "$var=false"
        else
            eval "DEFAULT_${var}_GOVERNOR=$(<"/var/lib/batman/default_${var,,}_governor")"
        fi
    fi
done

# hotplug has to be disabled for cpu cores to be allowed to go offline.
if [ "$IS_EXYNOS" == "true" ]; then
   if [ -f /sys/power/cpuhotplug/enabled ]; then
      echo 0 > /sys/power/cpuhotplug/enabled
   fi
fi

if [ "$CPUSAVEGOVERNOR" == "exynos_cpu_limit" ]; then
   RUNTIME_CUR_GOVERNOR=$DEFAULT_GOVERNOR
fi

# on some (if not all) exynos chips powersave doesn't exist so we need an alternative ways of lowering clock speeds
# like to set governor to userspace and set scaling_min_freq to scaling_setspeed to get the minimum frequency at idle.
if [ "$CPUSAVEGOVERNOR" == "powersave" ]; then
    function powersave() {
        for ((i=$CORE_FIRST; i<=$CORE_LAST; i++))
        do
            echo "$CPUSAVEGOVERNOR" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
        done
    }
elif [ "$CPUSAVEGOVERNOR" == "userspace" ]; then
    function powersave() {
        for ((i=$CORE_FIRST; i<=$CORE_LAST; i++))
        do
            echo "$CPUSAVEGOVERNOR" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
            MINFREQ=$(</sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq)
            echo $MINFREQ > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_setspeed
            RUNTIME_CUR_GOVERNOR="powersave"
        done
    }
elif [ "$CPUSAVEGOVERNOR" == "exynos_cpu_limit" ]; then
    function powersave() {
        echo "$CPUFREQ_MIN_LIMIT" > /sys/power/cpufreq_max_limit
        RUNTIME_CUR_GOVERNOR="powersave"
    }
else
    function powersave() {
        :
    }
fi

# same story as above basically
if [ "$CPUSAVEGOVERNOR" == "powersave" ]; then
    function default() {
        for ((i=$CORE_FIRST; i<=$CORE_LAST; i++))
        do
            echo "$DEFAULT_GOVERNOR" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
        done
    }
elif [ "$CPUSAVEGOVERNOR" == "userspace" ]; then
    function default() {
        for ((i=$CORE_FIRST; i<=$CORE_LAST; i++))
        do
            echo "$CPUSAVEGOVERNOR" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
            MAXFREQ=$(</sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq)
            echo $MAXFREQ > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_setspeed
            RUNTIME_CUR_GOVERNOR=$DEFAULT_GOVERNOR
        done
    }
elif [ "$CPUSAVEGOVERNOR" == "exynos_cpu_limit" ]; then
    function default() {
        echo "$CPUFREQ_MAX_LIMIT" > /sys/power/cpufreq_max_limit
        echo "$CPUFREQ_MAX_LIMIT" > /sys/power/cpufreq_min_limit
        RUNTIME_CUR_GOVERNOR=$DEFAULT_GOVERNOR
    }
else
    function default() {
       :
    }
fi

# some chipsets will crash the entire kernel if we set core 0 to offline so lets declare separate functions for them
if [ "$CPUSAVEGOVERNOR" == "powersave" ] || [ "$CPUSAVEGOVERNOR" == "userspace" ]; then
    function offline() {
        for ((i=$FIRSTPOLCORE; i<=$LASTPOLCORE; i++))
        do
             echo "0" > /sys/devices/system/cpu/cpu$i/online
        done
    }
elif [ "$CPUSAVEGOVERNOR" == "exynos_cpu_limit" ]; then
    function offline() {
        for ((i=1; i<=$LASTPOLCORE; i++))
        do
             echo "0" > /sys/devices/system/cpu/cpu$i/online
        done
    }
else
    function offline() {
       :
    }
fi

# same story as above but the opposite
if [ "$CPUSAVEGOVERNOR" == "powersave" ] || [ "$CPUSAVEGOVERNOR" == "userspace" ]; then
    function online() {
        for ((i=$FIRSTPOLCORE; i<=$LASTPOLCORE; i++))
        do
             echo "1" > /sys/devices/system/cpu/cpu$i/online
        done
    }
elif [ "$CPUSAVEGOVERNOR" == "exynos_cpu_limit" ]; then
    function online() {
        for ((i=1; i<=$LASTPOLCORE; i++))
        do
             echo "1" > /sys/devices/system/cpu/cpu$i/online
        done
    }
else
    function online() {
       :
    }
fi

function gpusave() {
   if [ "$GPUSAVE" == "true" ] && [ "$CAN_GPUSAVE" == "true" ]; then
      echo "powersave" > $GPU_GOVERNOR_PATH
   fi
}

function gpudefault() {
   if [ "$GPUSAVE" == "true" ] && [ "$CAN_GPUSAVE" == "true" ]; then
      echo "$DEFAULT_GPU_GOVERNOR" > $GPU_GOVERNOR_PATH
   fi
}

# Check if BUSSAVE is enabled, if so enable use the right functions.
function bussave() {
   if [ "$BUSSAVE" == "true" ]; then
      if [ "$CCI" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cci/governor
      fi

      if [ "$CPUBW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpubw/governor
      fi

      if [ "$GPUBW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,gpubw/governor
      fi

      if [ "$KGSL_BUSMON" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,kgsl-busmon/governor
      fi

      if [ "$MINCPUBW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,mincpubw/governor
      fi

#       if [ "$L3CPU0" == "true" ]; then
#          echo "powersave" > /sys/class/devfreq/soc:qcom,l3-cpu0/governor
#       fi

#       if [ "$L3CPU6" == "true" ]; then
#          echo "powersave" > /sys/class/devfreq/soc:qcom,l3-cpu6/governor
#       fi

      if [ "$ARM9_BUS_DDR" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/aa00000.qcom,vidc1:arm9_bus_ddr/governor
      fi

      if [ "$BUS_CNOC" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/aa00000.qcom,vidc1:bus_cnoc/governor
      fi

#       if [ "$VENUS_BUS_DDR" == "true" ]; then
#          echo "powersave" > /sys/class/devfreq/aa00000.qcom,vidc1:venus_bus_ddr/governor
#       fi

      if [ "$L3CDSP" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,l3-cdsp/governor
      fi

      if [ "$MEMLAT_CPU0" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,memlat-cpu0/governor
      fi

      if [ "$MEMLAT_CPU4" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,memlat-cpu4/governor
      fi

      if [ "$MEMLAT_CPU6" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,memlat-cpu6/governor
      fi

      if [ "$MINCPU0BW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,mincpu0bw/governor
      fi

      if [ "$MINCPU6BW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,mincpu6bw/governor
      fi

      if [ "$DEVFREQ_SQPM_CPU" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:devfreq_spdm_cpu/governor
      fi

      if [ "$CDSP_CDSP_L3_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cdsp-cdsp-l3-lat/governor
      fi

      if [ "$CPU0_CPU_DDR_LATFLOOR" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-latfloor/governor
      fi

      if [ "$CPU0_CPU_L3_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu0-cpu-l3-lat/governor
      fi

      if [ "$CPU0_CPU_LLCC_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu0-cpu-llcc-lat/governor
      fi

      if [ "$CPU0_LLCC_DDR_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/governor
      fi

      if [ "$CPU6_CPU_DDR_LATFLOOR" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu6-cpu-ddr-latfloor/governor
      fi

      if [ "$CPU6_CPU_L3_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu6-cpu-l3-lat/governor
      fi

      if [ "$CPU6_CPU_LLCC_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu6-cpu-llcc-lat/governor
      fi

      if [ "$CPU6_LLCC_DDR_LAT" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu6-llcc-ddr-lat/governor
      fi

      if [ "$CPU_CPU_LLCC_BW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu-cpu-llcc-bw/governor
      fi

      if [ "$CPU_LLCC_DDR_BW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/governor
      fi

      if [ "$NPUDSP_NPU_DDR_BW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,npudsp-npu-ddr-bw/governor
      fi

      if [ "$NPU_NPU_DDR_BW" == "true" ]; then
         echo "powersave" > /sys/class/devfreq/soc:qcom,npu-npu-ddr-bw/governor
      fi
      :
   fi
}

function busdefault() {
   if [ "$BUSSAVE" == "true" ]; then
      if [ "$CCI" == "true" ]; then
         echo "$DEFAULT_CCI_GOVERNOR" > /sys/class/devfreq/soc:qcom,cci/governor
      fi

      if [ "$CPUBW" == "true" ]; then
         echo "$DEFAULT_CPUBW_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpubw/governor
      fi

      if [ "$GPUBW" == "true" ]; then
         echo "$DEFAULT_GPUBW_GOVERNOR" > /sys/class/devfreq/soc:qcom,gpubw/governor
      fi

      if [ "$KGSL_BUSMON" == "true" ]; then
         echo "$DEFAULT_KGSL_BUSMON_GOVERNOR" > /sys/class/devfreq/soc:qcom,kgsl-busmon/governor
      fi

      if [ "$MINCPUBW" == "true" ]; then
         echo "$DEFAULT_MINCPUBW_GOVERNOR" > /sys/class/devfreq/soc:qcom,mincpubw/governor
      fi

#       if [ "$L3CPU0" == "true" ]; then
#          echo "$DEFAULT_L3CPU0_GOVERNOR" > /sys/class/devfreq/soc:qcom,l3-cpu0/governor
#       fi

#       if [ "$L3CPU6" == "true" ]; then
#          echo "$DEFAULT_L3CPU6_GOVERNOR" > /sys/class/devfreq/soc:qcom,l3-cpu6/governor
#       fi

      if [ "$ARM9_BUS_DDR" == "true" ]; then
         echo "$DEFAULT_ARM9_BUS_DDR_GOVERNOR" > /sys/class/devfreq/aa00000.qcom,vidc1:arm9_bus_ddr/governor
      fi

      if [ "$BUS_CNOC" == "true" ]; then
         echo "$DEFAULT_BUS_CNOC_GOVERNOR" > /sys/class/devfreq/aa00000.qcom,vidc1:bus_cnoc/governor
      fi

#       if [ "$VENUS_BUS_DDR" == "true" ]; then
#          echo "$DEFAULT_VENUS_BUS_DDR_GOVERNOR" > /sys/class/devfreq/aa00000.qcom,vidc1:venus_bus_ddr/governor
#       fi

      if [ "$L3CDSP" == "true" ]; then
         echo "$DEFAULT_L3CDSP_GOVERNOR" > /sys/class/devfreq/soc:qcom,l3-cdsp/governor
      fi

      if [ "$MEMLAT_CPU0" == "true" ]; then
         echo "$DEFAULT_MEMLAT_CPU0_GOVERNOR" > /sys/class/devfreq/soc:qcom,memlat-cpu0/governor
      fi

      if [ "$MEMLAT_CPU4" == "true" ]; then
         echo "$DEFAULT_MEMLAT_CPU4_GOVERNOR" > /sys/class/devfreq/soc:qcom,memlat-cpu4/governor
      fi

      if [ "$MEMLAT_CPU6" == "true" ]; then
         echo "$DEFAULT_MEMLAT_CPU6_GOVERNOR" > /sys/class/devfreq/soc:qcom,memlat-cpu6/governor
      fi

      if [ "$MINCPU0BW" == "true" ]; then
         echo "$DEFAULT_MINCPU0BW_GOVERNOR" > /sys/class/devfreq/soc:qcom,mincpu0bw/governor
      fi

      if [ "$MINCPU6BW" == "true" ]; then
         echo "$DEFAULT_MINCPU6BW_GOVERNOR" > /sys/class/devfreq/soc:qcom,mincpu6bw/governor
      fi

      if [ "$DEVFREQ_SQPM_CPU" == "true" ]; then
         echo "$DEFAULT_DEVFREQ_SQPM_CPU_GOVERNOR" > /sys/class/devfreq/soc:devfreq_spdm_cpu/governor
      fi

      if [ "$CDSP_CDSP_L3_LAT" == "true" ]; then
         echo "$DEFAULT_CDSP_CDSP_L3_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cdsp-cdsp-l3-lat/governor
      fi

      if [ "$CPU0_CPU_DDR_LATFLOOR" == "true" ]; then
         echo "$DEFAULT_CPU0_CPU_DDR_LATFLOOR_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-latfloor/governor
      fi

      if [ "$CPU0_CPU_L3_LAT" == "true" ]; then
         echo "$DEFAULT_CPU0_CPU_L3_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu0-cpu-l3-lat/governor
      fi

      if [ "$CPU0_CPU_LLCC_LAT" == "true" ]; then
         echo "$DEFAULT_CPU0_CPU_LLCC_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu0-cpu-llcc-lat/governor
      fi

      if [ "$CPU0_LLCC_DDR_LAT" == "true" ]; then
         echo "$DEFAULT_CPU0_LLCC_DDR_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/governor
      fi

      if [ "$CPU6_CPU_DDR_LATFLOOR" == "true" ]; then
         echo "$DEFAULT_CPU6_CPU_DDR_LATFLOOR_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu6-cpu-ddr-latfloor/governor
      fi

      if [ "$CPU6_CPU_L3_LAT" == "true" ]; then
         echo "$DEFAULT_CPU6_CPU_L3_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu6-cpu-l3-lat/governor
      fi

      if [ "$CPU6_CPU_LLCC_LAT" == "true" ]; then
         echo "$DEFAULT_CPU6_CPU_LLCC_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu6-cpu-llcc-lat/governor
      fi

      if [ "$CPU6_LLCC_DDR_LAT" == "true" ]; then
         echo "$DEFAULT_CPU6_LLCC_DDR_LAT_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu6-llcc-ddr-lat/governor
      fi

      if [ "$CPU_CPU_LLCC_BW" == "true" ]; then
         echo "$DEFAULT_CPU_CPU_LLCC_BW_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu-cpu-llcc-bw/governor
      fi

      if [ "$CPU_LLCC_DDR_BW" == "true" ]; then
         echo "$DEFAULT_CPU_LLCC_DDR_BW_GOVERNOR" > /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/governor
      fi

      if [ "$NPUDSP_NPU_DDR_BW" == "true" ]; then
         echo "$DEFAULT_NPUDSP_NPU_DDR_BW_GOVERNOR" > /sys/class/devfreq/soc:qcom,npudsp-npu-ddr-bw/governor
      fi

      if [ "$NPU_NPU_DDR_BW" == "true" ]; then
         echo "$DEFAULT_NPU_NPU_DDR_BW_GOVERNOR" > /sys/class/devfreq/soc:qcom,npu-npu-ddr-bw/governor
      fi
      :
   fi
}

function btsave {
   if [ "$BTSAVE" == "true" ]; then
      if [ "$BTSTAT" == "on" ]; then
         if ! bluetoothctl info | grep -q 'Connected:'; then
            bluetoothctl power off > /dev/null 2>&1 &
            BTSTAT="off"
         fi
      fi
   fi
}

function btdefault {
   if [ "$BTSAVE" == "true" ] && [ "$BTSTAT" == "off" ]; then
      bluetoothctl power on > /dev/null 2>&1 &
      BTSTAT="on"
   fi
}

# This clears the screen status whether or not it is off.
echo "" > /var/lib/batman/screen

# Give ownership of /var/lib/batman to the user id available in /run/user.
chown -R $UIDS:$UIDS /var/lib/batman

while [[ true ]]
do
    # Save screen status of the last run to a variable so that we can use it later in our checks. (will be filled after the first run)
    SCREEN_OLD=$(</var/lib/batman/screen)

    # Get cpu usage from /proc/stat
    CPU_USAGE=$(eval "$GET_CPU_USAGE")

    # Save screen status to a variable so that we can use it later in our checks.
    SCREEN=$(eval "$GET_SCREEN")

    if [ "$KDE" == "true" ]; then
        if [ "$SCREEN" == "true" ]; then
           SCREEN="no"
        else
           SCREEN="yes"
        fi
    fi

    if [ "$CHARGESAVE" == "true" ]; then
        CHARGE="discharging"
    else
        # Check if device is plugged into a power source.
        CHARGE=$(eval "$GET_CHARGE")
    fi

    # on x86 devices mostly operate in powersave anyways so we should check
    # if device is plugged into a power source then set the governor to performance
    if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
       if [ "$CHARGE" = "charging" ] || [ "$CHARGE" = "fully-charged" ]; then
          DEFAULT_GOVERNOR="performance"
       else
          DEFAULT_GOVERNOR="powersave"
       fi
    fi

    # Check if powersave should be set.
    if [ "$POWERSAVE" == "true" ]; then
       # if screen is off and device is not charging then device will be set into powersave.
       if [ "$SCREEN_OLD" != "$SCREEN" ] && [ "$CHARGE" == "discharging" ] && [ "$SCREEN" == "no" ]; then
          powersave
          gpusave
          bussave
          btsave
       # if device is charging or fully charged and still plugged into the wall then set everything back to default. this behaviour can be changed by setting CHARGESAVE to true.
       elif [ "$SCREEN_OLD" != "$SCREEN" ] && [ "$CHARGE" == "charging" ] || [ "$CHARGE" == "fully-charged" ]; then
          default
          gpudefault
          busdefault
          btdefault
       # if screen is on (user using the device) set everything back to default.
       elif [ "$SCREEN" == "yes" ]; then
          default
          gpudefault
          busdefault
          btdefault
       fi
    fi

    # Save the current governor (check what has happened in the last run) so that if it is set to powersave we can use this info in our cpu offlining.
    if [ -z "$RUNTIME_CUR_GOVERNOR" ]; then
       CUR_GOVERNOR=$(</sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
    else
       CUR_GOVERNOR=$RUNTIME_CUR_GOVERNOR
    fi

    if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
       if [ "$SCREEN" = "no" ]; then
          SCREEN_OLD=yes
       fi

       DEFAULT_GOVERNOR="performance"
       CHARGE='discharging'
    fi

    # Use our OFFLINE variable to see if this process should even be started.
    if [ "$OFFLINE" == "true" ]; then
       # if device is not plugged into a power source and screen is off and cpu usage is less than MAX_CPU_USAGE (default is 60) then set cpu to offline.
       if [ "$SCREEN_OLD" != "$SCREEN" ] && [ "$CHARGE" == "discharging" ] && [ "$SCREEN" == "no" ] && [ "$CPU_USAGE" -le "$MAX_CPU_USAGE" ]; then
          offline
       # if screen or on or current governor is the same as default governor or cpu usage is higher than MAX_CPU_USAGE (default is 60) set cpu cores to online.
       elif [ "$SCREEN" == "yes" ] || [ "$CUR_GOVERNOR" == "$DEFAULT_GOVERNOR" ] || [ "$CPU_USAGE" -gt "$MAX_CPU_USAGE" ]; then
          online
       # if device is powersave (which means device is sleeping) then set cpu cores to offline.
       elif [ "$SCREEN_OLD" == "$SCREEN" ] && [ "$CUR_GOVERNOR" == "powersave" ]; then
          offline
       fi
    fi

    if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "i686" ]; then
       # on x86 chips batman will be intrerrupted if device gets suspended but we can fix this by checking if we can read a file
       # that is usually unavailable when cpu cores are set to offline and set the status accordingly to leave that unexpected state.
       if [ "$SCREEN" == "yes" ]; then
          if ! cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor > /dev/null 2>&1; then
             online
             default
             gpudefault
             busdefault
          fi
       fi
    fi

    # Put old status of screen into a file so that we can use it in the next run of this loop to lower cpu and memory usage later on.
    if [ "$SCREEN_OLD" != "$SCREEN" ]; then
       echo "$SCREEN" > /var/lib/batman/screen
    fi

    # To not do as many useless iterations wait here for some time when the screen is on or when user is using the device.
    if [ "$SCREEN" == "yes" ]; then
       if [ "$SCREEN_OLD" == "no" ]; then
          delay 0.3
       else
          delay 10
          source <(tail -n +2 /var/lib/batman/config)
       fi
    else
       delay 0.3
    fi
done
